language: python

services:
    - docker

before_script:
    - git clone https://github.com/icpc-jag/rime.git

script:
    - docker build -t bluejamkmy/rime-docker .
    - cp Dockerfile.example rime/example/Dockerfile
    - pushd rime/example
    - docker build -t rime-example .
    - docker run -it rime-example rime test
    - popd
