language: python

services:
    - docker

before_script:
    - git clone https://github.com/icpc-jag/rime.git

script:
    - docker build -t bluejamkmy/rime-docker .
    - cp Dockerfile.example rime/example/Dockerfile
    - pushd rime/example
    - docker build -t rime-example .
    - docker run -it rime-example rime test
    - popd

deploy:
    provider: script
    script:
        - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USER" --password-stdin >/dev/null 2>&1
        - docker push bluejamkmy/rime-docker
    on:
        repo: blue-jam/rime-docker
        branch: master
