language: python

services:
    - docker

before_install:
    - docker build -t bluejamkmy/rime-docker .
    - docker run bluejamkmy/rime-docker /bin/bash -c "git clone https://github.com/icpc-jag/rime.git"

script:
    - docker run bluejamkmy/rime-docker /bin/bash -c "cd /rime/example; rime test"
