language: python

services:
    - docker

script:
    - docker build -t bluejamkmy/rime-docker .
    - docker run --name rime-container bluejamkmy/rime-docker /bin/bash -c "git clone https://github.com/icpc-jag/rime.git; cd /rime/example; rime test"
