language: python

services:
    - docker

before_script:
    - git clone https://github.com/icpc-jag/rime.git

jobs:
    include:
        - stage: test
          script:
            - docker build -t bluejamkmy/rime-docker .
            - cp Dockerfile.example rime/example/Dockerfile
            - pushd rime/example
            - docker build -t rime-example .
            - docker run -it rime-example rime test
            - popd
        - stage: deploy
          script: curl -X POST ${BUILD_TRIGGER_URL} > /dev/null 2> /dev/null
          if: branch = master AND type = cron
